// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.localiza.arquitetura
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	/// <summary>
	/// Schema de exemplo para aprendizado do Kafka
	/// </summary>
	public partial class welcome_kafka : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"welcome_kafka\",\"namespace\":\"com.localiza.arquitetura\",\"f" +
				"ields\":[{\"name\":\"id\",\"doc\":\"Identidade da mensagem.\",\"type\":\"int\"},{\"name\":\"mens" +
				"agem\",\"doc\":\"Qualquer mensagem de teste\",\"type\":\"string\"}]}");
		/// <summary>
		/// Identidade da mensagem.
		/// </summary>
		private int _id;
		/// <summary>
		/// Qualquer mensagem de teste
		/// </summary>
		private string _mensagem;
		public virtual Schema Schema
		{
			get
			{
				return welcome_kafka._SCHEMA;
			}
		}
		/// <summary>
		/// Identidade da mensagem.
		/// </summary>
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		/// <summary>
		/// Qualquer mensagem de teste
		/// </summary>
		public string mensagem
		{
			get
			{
				return this._mensagem;
			}
			set
			{
				this._mensagem = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.mensagem;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.Int32)fieldValue; break;
			case 1: this.mensagem = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
